version: '2'
services:
  seedbloom-blog:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    links:
      - mongo
  mongo:
    container_name: 'mongo'
    image: mongo:3.4
    volumes:
      - ./data:/data/db